@echo off
chcp 936 >nul
cd /d "%~dp0"
set "DALANG_WB=%~dp0"

powershell -NoProfile -ExecutionPolicy Bypass -EncodedCommand JAB3AGIAIAA9ACAAJABlAG4AdgA6AEQAQQBMAEEATgBHAF8AVwBCAAoAJABkAGUAcwBrAHQAbwBwACAAPQAgAFsARQBuAHYAaQByAG8AbgBtAGUAbgB0AF0AOgA6AEcAZQB0AEYAbwBsAGQAZQByAFAAYQB0AGgAKAAnAEQAZQBzAGsAdABvAHAAJwApAAoAJAB3AHMAIAA9ACAATgBlAHcALQBPAGIAagBlAGMAdAAgAC0AQwBvAG0ATwBiAGoAZQBjAHQAIABXAFMAYwByAGkAcAB0AC4AUwBoAGUAbABsAAoAJABsAG4AawAgAD0AIAAkAHcAcwAuAEMAcgBlAGEAdABlAFMAaABvAHIAdABjAHUAdAAoACgASgBvAGkAbgAtAFAAYQB0AGgAIAAkAGQAZQBzAGsAdABvAHAAIAAnACdZam1LYDFy5V1cT/BTLgBsAG4AawAnACkAKQAKACQAbABuAGsALgBUAGEAcgBnAGUAdABQAGEAdABoACAAPQAgACgASgBvAGkAbgAtAFAAYQB0AGgAIAAkAHcAYgAgACcAcwB0AGEAcgB0AC4AYgBhAHQAJwApAAoAJABsAG4AawAuAFcAbwByAGsAaQBuAGcARABpAHIAZQBjAHQAbwByAHkAIAA9ACAAJAB3AGIACgAkAGwAbgBrAC4ASQBjAG8AbgBMAG8AYwBhAHQAaQBvAG4AIAA9ACAAKAAkAGUAbgB2ADoAUwB5AHMAdABlAG0AUgBvAG8AdAAgACsAIAAnAFwAUwB5AHMAdABlAG0AMwAyAFwAUwBIAEUATABMADMAMgAuAGQAbABsACwAMgAyADAAJwApAAoAJABsAG4AawAuAEQAZQBzAGMAcgBpAHAAdABpAG8AbgAgAD0AIAAnACdZam1LYDFy5V1cT/BTIAC3ACAAfVkfYdF2p2NoVicACgAkAGwAbgBrAC4AUwBhAHYAZQAoACkA

echo.
echo  ============================================
echo   桌面快捷方式「大浪恋爱工作台」已创建！
echo   以后双击桌面的「大浪恋爱工作台」即可一键启动。
echo  ============================================
echo.
pause
